config/routes.rb
Osc::Application.routes.draw do
  
  get "tags/index"

  get "tags/show"

  match '/welcome', :controller  => 'welcome', :action  =>  'index'
  match '/users/login', :controller => 'users', :action => 'login'
  match '/users/register', :controller  => 'users', :action  =>  'new'
  resources :users
  resources :sessions
  resources :news
  resources :racingteams
  resources :tags

  root :to => 'welcome#index'
  get "welcome/index"
  get "welcome/learntoski"
  get "welcome/aboutus"
  get "welcome/contactus"
  get "welcome/faqs"
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :city, :county, :email, :firstname, :lastname, :mobile, :password, :postcode, :street, :username
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
  
  def login
    
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
<% if @user.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

	<ul>
		<% @user.errors.full_messages.each do |msg| %>
		<li>
			<%= msg %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>

<div class="form-wrap">
	<h5>Personal Details:</h5>
	<table class="table table-condensed">
		<tr>
			<td>
			<div class="field">
				<%= f.text_field :firstname, :placeholder => "First Name", :required => "true" %>
			</div>
			<div class="field">
				<%= f.text_field :lastname, :placeholder => "Last Name", :required => "true" %>
			</div>
			<div class="field">
				<%= f.text_field :street, :placeholder => "Street", :required => "true" %>
			</div>
			<div class="field">
				<%= f.text_field :city, :placeholder => "City", :required => "true" %>
			</div></td>
			<td>
			<div class="field">
				<%= f.text_field :postcode, :placeholder => "Postcode", :required => "true" %>
			</div>
			<div class="field">
				<%= f.text_field :county, :placeholder => "County", :required => "true" %>
			</div>
			<div class="field">
				<%= f.text_field :mobile, :placeholder => "Mobile"  %>
			</div>
			<div class="field">
				<%= f.text_field :email, :placeholder => "Email", :required => "true" %>
			</div></td>
		</tr>
	</table>
</div>
<div class="form-wrap">
	<h5>Account Details:</h5>
	<div id="account-fields">
		<table class="table table-condensed">
			<tr>
				<td>
				<div class="field">
					<%= f.text_field :username, :placeholder => "Username", :required => "true" %>
				</div></td>
				<td>
				<div class="field">
					<%= f.text_field :password, :placeholder => "Password", :type => "password", :required => "true" %>
				</div></td>
			</tr>
		</table>
	</div>
</div>
<div class="actions">
	<%= f.submit(:class => "blue-pill", :value => "Register") %>
</div>
<% end %>

app/views/users/edit.html.erb
<%= Navigation() %>
<div class="content">
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>
</div>

app/views/users/index.html.erb
<%= Navigation("register") %>

<h1>Listing users</h1>

<table>
  <tr>
    <th>Firstname</th>
    <th>Lastname</th>
    <th>Street</th>
    <th>City</th>
    <th>Postcode</th>
    <th>County</th>
    <th>Mobile</th>
    <th>Email</th>
    <th>Username</th>
    <th>Password</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.firstname %></td>
    <td><%= user.lastname %></td>
    <td><%= user.street %></td>
    <td><%= user.city %></td>
    <td><%= user.postcode %></td>
    <td><%= user.county %></td>
    <td><%= user.mobile %></td>
    <td><%= user.email %></td>
    <td><%= user.username %></td>
    <td><%= user.password %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/login.html.erb
<%= Navigation("login") %>

<div class="content">
	<h1>Login</h1>
	
	<%= form_for(@user) do |f| %>
	<div class="form-wrap">
		<h5>Account Details:</h5>
		<div id="account-fields">
			<table class="table table-condensed">
				<tr>
					<td>
					<div class="field">
						<%= f.text_field :username, :placeholder => "Username", :required => "true" %>
					</div></td>
					<td>
					<div class="field">
						<%= f.text_field :password, :placeholder => "Password", :type => "password", :required => "true" %>
					</div></td>
				</tr>
			</table>
		</div>
	</div>
	<div class="actions">
		<%= f.submit(:class => "blue-pill", :value => "Login") %>
	</div>
	<% end %>

</div>

app/views/users/new.html.erb
<%= Navigation("register") %>

<div class="content">
	<h1>Registration</h1>
	
	<%= render 'form' %>
	
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Firstname:</b>
  <%= @user.firstname %>
</p>

<p>
  <b>Lastname:</b>
  <%= @user.lastname %>
</p>

<p>
  <b>Street:</b>
  <%= @user.street %>
</p>

<p>
  <b>City:</b>
  <%= @user.city %>
</p>

<p>
  <b>Postcode:</b>
  <%= @user.postcode %>
</p>

<p>
  <b>County:</b>
  <%= @user.county %>
</p>

<p>
  <b>Mobile:</b>
  <%= @user.mobile %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Username:</b>
  <%= @user.username %>
</p>

<p>
  <b>Password:</b>
  <%= @user.password %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>