config/routes.rb
Osc::Application.routes.draw do
  
  get "tags/index"

  get "tags/show"

  match '/welcome', :controller  => 'welcome', :action  =>  'index'
  match '/users/login', :controller => 'users', :action => 'login'
  match '/users/register', :controller  => 'users', :action  =>  'new'
  resources :users
  resources :sessions
  resources :news
  resources :racingteams
  resources :tags

  root :to => 'welcome#index'
  get "welcome/index"
  get "welcome/learntoski"
  get "welcome/aboutus"
  get "welcome/contactus"
  get "welcome/faqs"
end

app/models/news.rb
class News < ActiveRecord::Base
  attr_accessible :body, :title
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  # GET /news
  # GET /news.json
  def index
    @news = News.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @news }
    end
  end

  # GET /news/1
  # GET /news/1.json
  def show
    @news = News.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @news }
    end
  end

  # GET /news/new
  # GET /news/new.json
  def new
    @news = News.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @news }
    end
  end

  # GET /news/1/edit
  def edit
    @news = News.find(params[:id])
  end

  # POST /news
  # POST /news.json
  def create
    @news = News.new(params[:news])

    respond_to do |format|
      if @news.save
        format.html { redirect_to @news, notice: 'Event was successfully created.' }
        format.json { render json: @news, status: :created, location: @news }
      else
        format.html { render action: "new" }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /news/1
  # PUT /news/1.json
  def update
    @news = News.find(params[:id])

    respond_to do |format|
      if @news.update_attributes(params[:news])
        format.html { redirect_to @news, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news = News.find(params[:id])
    @news.destroy

    respond_to do |format|
      format.html { redirect_to news_index_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/news/_form.html.erb
<%= form_for(@news) do |f| %>
  <% if @news.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@news.errors.count, "error") %> prohibited this news from being saved:</h2>

      <ul>
      <% @news.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label "Announcement" %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit(:value  => "Save Event",:class  => "blue-pill") %>
  </div>
<% end %>

<script type="text/javascript">bkLib.onDomLoaded(nicEditors.allTextAreas);</script>

app/views/news/edit.html.erb
<%= Navigation() %>

<div class="content">
<h1>Editing news</h1>

<%= render 'form' %>

<%= link_to 'Show', @news, :class  => "blue-pill" %>
<%= link_to 'Back', news_index_path, :class  =>  "blue-pill" %>
</div>

app/views/news/index.html.erb
<%= Navigation() %>

<div class="content">
	<h1>Manage Anouncements</h1>
	<br/>
	<% @news.each do |news| %>
	<h4><%= news.title %></h4>
	<p>
		<%= news.body.html_safe %>
	</p>
	<hr/>
	<%= link_to 'Show', news %>
	<%= link_to 'Edit', edit_news_path(news) %>
	<%= link_to 'Destroy', news, method: :delete, data: { confirm: 'Are you sure?' } %>
	<hr/>
	<% end %>
	<br />
	<%= link_to 'Add New Announcement', new_news_path, :class => "blue-pill" %>
</div>

app/views/news/new.html.erb
<%= Navigation() %>

<div class="content">
<h1>Make a New Announcment</h1>

<%= render 'form' %>

<%= link_to 'Back', news_index_path, :class  => "blue-pill" %>
</div>

app/views/news/show.html.erb
<%= Navigation() %>

<div class="content">
	<% if notice!=nil %>
	<div class="alert alert-success">
		<%= notice %>
	</div>
	<% end %>
	
	<h4><%= @news.title %></h4>
	<div class="para-wrap">
	<p><%= @news.body.html_safe %></p>
	</div>
	<br/>
	<%= link_to 'Edit', edit_news_path(@news), :class  => "blue-pill" %>
	<%= link_to 'Back', news_index_path, :class  =>  "blue-pill" %>
</div>