config/routes.rb
Osc::Application.routes.draw do
  
  get "tags/index"

  get "tags/show"

  match '/welcome', :controller  => 'welcome', :action  =>  'index'
  match '/users/login', :controller => 'users', :action => 'login'
  match '/users/register', :controller  => 'users', :action  =>  'new'
  resources :users
  resources :sessions
  resources :news
  resources :racingteams
  resources :tags

  root :to => 'welcome#index'
  get "welcome/index"
  get "welcome/learntoski"
  get "welcome/aboutus"
  get "welcome/contactus"
  get "welcome/faqs"
end

app/models/racingteam.rb
class Racingteam < ActiveRecord::Base
  has_many :taggings
  has_many :tags, through: :taggings
  attr_accessible :body, :title, :tag_list
  
  def tag_list
    self.tags.collect do  |tag|
      tag.name
    end.join(", ")
  end
  
  def to_s
    name
  end
  
  def tag_list=(tags_string)
    self.taggings.destroy_all
    tag_names = tags_string.split(", ").collect{|s| s.strip.downcase}.uniq
    
    tag_names.each do |tag_name|
      tag = Tag.find_or_create_by_name(tag_name)
      tagging = self.taggings.new
      tagging.tag_id = tag.id
    end
  end
end

app/controllers/racingteams_controller.rb
class RacingteamsController < ApplicationController
  # GET /racingteams
  # GET /racingteams.json
  def index
    @racingteams = Racingteam.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @racingteams }
    end
  end

  # GET /racingteams/1
  # GET /racingteams/1.json
  def show
    @racingteam = Racingteam.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @racingteam }
    end
  end

  # GET /racingteams/new
  # GET /racingteams/new.json
  def new
    @racingteam = Racingteam.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @racingteam }
    end
  end

  # GET /racingteams/1/edit
  def edit
    @racingteam = Racingteam.find(params[:id])
  end

  # POST /racingteams
  # POST /racingteams.json
  def create
    @racingteam = Racingteam.new(params[:racingteam])

    respond_to do |format|
      if @racingteam.save
        format.html { redirect_to @racingteam, notice: 'Event was successfully created.' }
        format.json { render json: @racingteam, status: :created, location: @racingteam }
      else
        format.html { render action: "new" }
        format.json { render json: @racingteam.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /racingteams/1
  # PUT /racingteams/1.json
  def update
    @racingteam = Racingteam.find(params[:id])

    respond_to do |format|
      if @racingteam.update_attributes(params[:racingteam])
        format.html { redirect_to @racingteam, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @racingteam.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /racingteams/1
  # DELETE /racingteams/1.json
  def destroy
    @racingteam = Racingteam.find(params[:id])
    @racingteam.destroy

    respond_to do |format|
      format.html { redirect_to racingteams_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/racingteams_helper.rb
module RacingteamsHelper
  def tag_links(tags)
    links = tags.collect{|tag| link_to tag.name, tag_path(tag)}
    return links.join(", ").html_safe
  end
end

app/views/racingteams/_form.html.erb
<%= form_for(@racingteam) do |f| %>
  <% if @racingteam.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@racingteam.errors.count, "error") %> prohibited this racingteam from being saved:</h2>

      <ul>
      <% @racingteam.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label "Announcement" %><br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
  	<%= f.label :tag_list %><br/>
  	<%= f.text_field :tag_list %>
  </div>
  <div class="actions">
    <%= f.submit(:value  => "Save Event", :class  => "blue-pill") %>
  </div>
<% end %>

app/views/racingteams/edit.html.erb
<%= Navigation("racingteam") %>

<div class="content">
<h4>Editing: <%= @racingteam.title %></h4>

<%= render 'form' %>

<%= link_to 'Show', @racingteam, :class  => 'blue-pill' %>
<%= link_to 'Back', racingteams_path, :class  => 'blue-pill' %>
</div>

<script type="text/javascript">bkLib.onDomLoaded(nicEditors.allTextAreas);</script>

app/views/racingteams/index.html.erb
<%= Navigation("racingteam") %>

<div class="content">
	<h1>Do you want to race?</h1>
	<p>
		All members of the ski club are eligible to race. It's a great way to improve your skiing so if you are interested in racing then contact Tony, or any member of the team, who will provide you with the information you need.
	</p>
	<p>
		Tony McClave, your race secretary works tirelessly behind the scenes to make the winter and summer racing possible. Tony can be seen down at the club for more information.
	</p>
	<h5>The races we enter...</h5>
	<p>
		We have members who race in the National league at various ski slopes across the country . We also organise teams to race at Stoke (in the summer), Sheffield (in the winter) and Pendle (also in the winter). Details for these local races can be found below.
	</p>
	<br/>
	<% @racingteams.each do |racingteam| %>
	<h3><%= racingteam.title %></h3>
	<p><%= racingteam.body.html_safe %></p>
	<p class="label label-info"><%= racingteam.tag_list %></p>
	<hr/>
	<%= link_to 'Show', racingteam %> | 
	<%= link_to 'Edit', edit_racingteam_path(racingteam) %> |  
	<%= link_to 'Destroy', racingteam, method: :delete, data: { confirm: 'Are you sure?' } %>
	<hr/>
	<% end %>

	<br/>
	<br/>

	<%= link_to 'Add New Event', new_racingteam_path, :class  => "blue-pill" %>
</div>

app/views/racingteams/new.html.erb
<%= Navigation("racingteam") %>

<div class="content">
<h1>Add New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', racingteams_path, :class => "blue-pill" %>
</div>

<script type="text/javascript">bkLib.onDomLoaded(nicEditors.allTextAreas);</script>

app/views/racingteams/show.html.erb
<%= Navigation("racingteam") %>

<div class="content">
	<% if notice!=nil %>
	<div class="alert alert-success">
		<%= notice %>
	</div>
	<% end %>
	<h4> <%= @racingteam.title %> </h4>
	<div class="para-wrap">
	<p><%= @racingteam.body.html_safe %></p>
	<p><%= tag_links(@racingteam.tags) %></p>
	</div>
	<br/>
	<%= link_to 'Edit', edit_racingteam_path(@racingteam), :class  => "blue-pill" %>
	<%= link_to 'Back', racingteams_path, :class  => "blue-pill" %>
</div>

<script type="text/javascript">bkLib.onDomLoaded(nicEditors.allTextAreas);</script>